// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClientDBManage(arg1) {
  return window['go']['main_control']['Control']['ClientDBManage'](arg1);
}

export function DriverFuzz(arg1, arg2) {
  return window['go']['main_control']['Control']['DriverFuzz'](arg1, arg2);
}

export function DriverParser(arg1, arg2, arg3) {
  return window['go']['main_control']['Control']['DriverParser'](arg1, arg2, arg3);
}

export function DynamicFormGenerate(arg1) {
  return window['go']['main_control']['Control']['DynamicFormGenerate'](arg1);
}

export function GetClientConfigOptionsWithName(arg1) {
  return window['go']['main_control']['Control']['GetClientConfigOptionsWithName'](arg1);
}

export function GetInfos(arg1) {
  return window['go']['main_control']['Control']['GetInfos'](arg1);
}

export function GetProxyBuff(arg1) {
  return window['go']['main_control']['Control']['GetProxyBuff'](arg1);
}

export function GetTaskStatus(arg1) {
  return window['go']['main_control']['Control']['GetTaskStatus'](arg1);
}

export function GetTasks(arg1) {
  return window['go']['main_control']['Control']['GetTasks'](arg1);
}

export function ReadDriverCache(arg1) {
  return window['go']['main_control']['Control']['ReadDriverCache'](arg1);
}

export function Startup(arg1) {
  return window['go']['main_control']['Control']['Startup'](arg1);
}

export function TaskPause(arg1) {
  return window['go']['main_control']['Control']['TaskPause'](arg1);
}

export function TaskStop(arg1) {
  return window['go']['main_control']['Control']['TaskStop'](arg1);
}
