// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common_model} from '../models';
import {models} from '../models';
import {zzz_models} from '../models';

export function ClientDBManage(arg1:common_model.DBManageReq):Promise<common_model.DBManageResp>;

export function DriverFuzz(arg1:string,arg2:models.DamageFuzzParam):Promise<zzz_models.DriverFuzzResp>;

export function DriverParser(arg1:string,arg2:Array<zzz_models.FileInfo>,arg3:string):Promise<zzz_models.DriverParserResp>;

export function DynamicFormGenerate(arg1:common_model.DynamicFormReq):Promise<common_model.DynamicFormResp>;

export function GetClientConfigOptionsWithName(arg1:string):Promise<common_model.CommonConfigOptionsResp>;

export function GetProxyBuff(arg1:zzz_models.TestProxyBuffReq):Promise<zzz_models.TestProxyBuffResp>;

export function GetTaskStatus(arg1:common_model.CommonReq):Promise<common_model.TaskStatusResp>;

export function GetTasks(arg1:common_model.CommonReq):Promise<common_model.TasksResp>;

export function ReadDriverCache(arg1:string):Promise<common_model.CommonBytesResp>;

export function Startup(arg1:any):Promise<void>;

export function TaskPause(arg1:common_model.TaskPauseReq):Promise<common_model.CommonResp>;

export function TaskStop(arg1:common_model.CommonReq):Promise<common_model.CommonResp>;
