// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {common_model} from '../models';
import {main} from '../models';

export function GC():Promise<common_model.CommonResp>;

export function GetAppStatus():Promise<main.AppStatus>;

export function LanguageEncode(arg1:common_model.LanguageEncodeReq):Promise<common_model.LanguageEncodeResp>;

export function LocalFileWrite(arg1:string,arg2:Array<number>,arg3:number):Promise<common_model.CommonResp>;

export function ReadFile(arg1:string):Promise<common_model.CommonBytesResp>;

export function Restart():Promise<common_model.CommonResp>;

export function WrapOpenDirectoryDialog(arg1:string):Promise<common_model.CommonResp>;

export function WrapOpenFileDialog(arg1:string):Promise<common_model.CommonResp>;

export function WrapSaveFileDialog(arg1:string):Promise<common_model.CommonResp>;

export function WriteFile(arg1:string,arg2:Array<number>):Promise<common_model.CommonResp>;
