// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GC() {
  return window['go']['main']['App']['GC']();
}

export function GetAppStatus() {
  return window['go']['main']['App']['GetAppStatus']();
}

export function LanguageEncode(arg1) {
  return window['go']['main']['App']['LanguageEncode'](arg1);
}

export function LocalFileWrite(arg1, arg2, arg3) {
  return window['go']['main']['App']['LocalFileWrite'](arg1, arg2, arg3);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function Restart() {
  return window['go']['main']['App']['Restart']();
}

export function WrapOpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['WrapOpenDirectoryDialog'](arg1);
}

export function WrapOpenFileDialog(arg1) {
  return window['go']['main']['App']['WrapOpenFileDialog'](arg1);
}

export function WrapSaveFileDialog(arg1) {
  return window['go']['main']['App']['WrapSaveFileDialog'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
